<?php
/**
 * Plugin Name: VeriFact Checker Pro
 * Description: Advanced WordPress UI + REST proxy for the VeriFact (FacTool + Retrieval) FastAPI service with comprehensive dashboard.
 * Version: 2.0.5
 * Author: Veracity Integrity
 * License: MIT
 * Requires at least: 5.8
 * Requires PHP: 7.4
 */
if (!defined('ABSPATH')) { exit; }
class VeriFactPlugin {
    const OPT_API_BASE = 'verifact_api_base';
    const OPT_API_KEY = 'verifact_api_key';
    const OPT_RATE_LIMIT = 'verifact_rate_limit';
    const OPT_CACHE_DURATION = 'verifact_cache_duration';
    const OPT_USER_PERMISSIONS = 'verifact_user_permissions';
    const NONCE_ACTION = 'verifact_nonce_action';
    public function __construct() {
        add_action('admin_menu', [$this, 'add_admin_menu']);
        add_action('admin_init', [$this, 'register_settings']);
        add_shortcode('verifact', [$this, 'shortcode']);
        add_action('wp_enqueue_scripts', [$this, 'enqueue_assets']);
        add_action('rest_api_init', [$this, 'register_rest']);
        add_action('admin_enqueue_scripts', [$this, 'admin_enqueue_scripts']);
        add_action('init', [$this, 'create_tables']);
        add_action('wp_ajax_verifact_bulk_check', [$this, 'ajax_bulk_check']);
        add_action('wp_ajax_verifact_get_stats', [$this, 'ajax_get_stats']);
        add_action('wp_ajax_verifact_clear_cache', [$this, 'ajax_clear_cache']);
        add_action('wp_ajax_verifact_create_schedule', [$this, 'ajax_create_schedule']);
        add_action('wp_ajax_verifact_get_log', [$this, 'ajax_get_log']);
        add_action('wp_ajax_verifact_get_user_stats', [$this, 'ajax_get_user_stats']);
        add_action('wp_ajax_verifact_upload_remote_cache', [$this, 'ajax_upload_remote_cache']);
        add_filter('cron_schedules', [$this, 'extend_cron_schedules']);
        add_action('verifact_run_schedules', [$this, 'run_schedules']);
        add_action('init', [$this, 'ensure_cron']);
    }
    public function create_tables() { global $wpdb; $table_name = $wpdb->prefix . 'verifact_logs'; $charset_collate = $wpdb->get_charset_collate(); $sql = "CREATE TABLE IF NOT EXISTS $table_name (id mediumint(9) NOT NULL AUTO_INCREMENT,claim text NOT NULL,stance varchar(20) NOT NULL,confidence decimal(3,2) NOT NULL,evidence_count int(11) NOT NULL,runtime_sec decimal(5,2) NOT NULL,user_id int(11) DEFAULT NULL,ip_address varchar(45) DEFAULT NULL,user_agent text DEFAULT NULL,created_at datetime DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (id),KEY user_id (user_id),KEY created_at (created_at),KEY stance (stance)) $charset_collate;"; require_once(ABSPATH . 'wp-admin/includes/upgrade.php'); dbDelta($sql); }
    public function add_admin_menu() { add_menu_page('VeriFact Dashboard','VeriFact','manage_options','verifact-dashboard',[$this,'dashboard_page'],'dashicons-search',30); add_submenu_page('verifact-dashboard','Dashboard','Dashboard','manage_options','verifact-dashboard',[$this,'dashboard_page']); add_submenu_page('verifact-dashboard','Fact-Checking','Fact-Checking','manage_options','verifact-checking',[$this,'fact_checking_page']); add_submenu_page('verifact-dashboard','Analytics','Analytics','manage_options','verifact-analytics',[$this,'analytics_page']); add_submenu_page('verifact-dashboard','History & Logs','History & Logs','manage_options','verifact-history',[$this,'history_page']); add_submenu_page('verifact-dashboard','Bulk Tools','Bulk Tools','manage_options','verifact-bulk',[$this,'bulk_tools_page']); add_submenu_page('verifact-dashboard','API Management','API Management','manage_options','verifact-api',[$this,'api_management_page']); add_submenu_page('verifact-dashboard','Settings','Settings','manage_options','verifact-settings',[$this,'settings_page']); add_submenu_page('verifact-dashboard','User Management','User Management','manage_options','verifact-users',[$this,'user_management_page']); }
    public function register_settings() { register_setting('verifact_settings', self::OPT_API_BASE, ['type'=>'string','sanitize_callback'=>'esc_url_raw','default'=>home_url('/verifact')]); register_setting('verifact_settings', self::OPT_API_KEY, ['type'=>'string','sanitize_callback'=>'sanitize_text_field','default'=>'']); register_setting('verifact_settings', self::OPT_RATE_LIMIT, ['type'=>'integer','sanitize_callback'=>'intval','default'=>100]); register_setting('verifact_settings', self::OPT_CACHE_DURATION, ['type'=>'integer','sanitize_callback'=>'intval','default'=>3600]); register_setting('verifact_settings', self::OPT_USER_PERMISSIONS, ['type'=>'array','sanitize_callback'=>[$this,'sanitize_user_permissions'],'default'=>['administrator']]); register_setting('verifact_settings', 'verifact_enable_archiveorg', ['type'=>'boolean','sanitize_callback'=>'rest_sanitize_boolean','default'=>0]); register_setting('verifact_settings', 'verifact_enable_grokopedia', ['type'=>'boolean','sanitize_callback'=>'rest_sanitize_boolean','default'=>0]); register_setting('verifact_settings', 'verifact_remote_cache_enabled', ['type'=>'boolean','sanitize_callback'=>'rest_sanitize_boolean','default'=>0]); register_setting('verifact_settings', 'verifact_remote_cache_url', ['type'=>'string','sanitize_callback'=>'esc_url_raw','default'=>'']); register_setting('verifact_settings', 'verifact_role_rate_limits', ['type'=>'string','sanitize_callback'=>'sanitize_text_field','default'=>'']); }
    public function admin_enqueue_scripts($hook) { if (strpos($hook, 'verifact') !== false) { wp_enqueue_style('verifact-admin-css', plugins_url('assets/verifact-admin.css', __FILE__), [], '2.0.5'); wp_enqueue_style('verifact-graphics-css', plugins_url('assets/verifact-graphics.css', __FILE__), ['verifact-admin-css'], '2.0.5'); wp_enqueue_style('verifact-widgets-css', plugins_url('assets/verifact-widgets.css', __FILE__), ['verifact-admin-css'], '2.0.5'); wp_enqueue_script('verifact-admin-js', plugins_url('assets/verifact-admin.js', __FILE__), ['jquery'], '2.0.5', true); wp_localize_script('verifact-admin-js', 'verifactAdmin', ['ajaxurl'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('verifact_admin_nonce')]); } }
    public function enqueue_assets() { wp_register_style('verifact-css', plugins_url('assets/verifact.css', __FILE__), [], '2.0.5'); wp_register_script('verifact-js', plugins_url('assets/verifact.js', __FILE__), [], '2.0.5', true); wp_localize_script('verifact-js', 'VeriFactCfg', ['restUrl'=>esc_url_raw(rest_url('verifact/v1/check')),'nonce'=>wp_create_nonce(self::NONCE_ACTION)]); }
    public function shortcode($atts) { wp_enqueue_style('verifact-css'); wp_enqueue_script('verifact-js'); ob_start(); ?><div id="verifact-root" class="verifact-card"></div><?php return ob_get_clean(); }
    public function register_rest() { register_rest_route('verifact/v1', '/check', ['methods'=>'POST','callback'=>[$this,'handle_check'],'permission_callback'=>[$this,'check_permissions']]); }
    public function handle_check(\WP_REST_Request $req) { $body = $req->get_json_params(); if (!$body) { return new \WP_Error('bad_request', 'JSON body required', ['status'=>400]); } if (!$this->enforce_rate_limit()) { return new \WP_Error('rate_limit', 'Rate limit exceeded', ['status'=>429]); } $payload = is_array($body)?$body:[]; $sources = []; if (get_option('verifact_enable_archiveorg',0)) { $sources[]='archiveorg'; } if (get_option('verifact_enable_grokopedia',0)) { $sources[]='grokopedia'; } if (!empty($sources)) { $payload['sources']=$sources; } $cache_key = 'verifact_cache_' . md5(wp_json_encode($payload)); $cache_ttl = (int) get_option(self::OPT_CACHE_DURATION, 3600); $cached = $this->cache_get($cache_key); if ($cached) { $data = json_decode($cached, true); $this->log_fact_check($payload, $data, $req); return new \WP_REST_Response($data, 200); } $api_base = rtrim(get_option(self::OPT_API_BASE, home_url('/verifact')), '/'); $url = $api_base . '/check'; $res = wp_remote_post($url, ['timeout'=>45,'headers'=>['Content-Type'=>'application/json'],'body'=>wp_json_encode($payload)]); if (is_wp_error($res)) { return new \WP_Error('upstream_error', $res->get_error_message(), ['status'=>502]); } $code = wp_remote_retrieve_response_code($res); $data = json_decode(wp_remote_retrieve_body($res), true); if ($cache_ttl > 0 && $data) { $this->cache_set($cache_key, wp_json_encode($data), $cache_ttl); } $this->log_fact_check($payload, $data, $req); return new \WP_REST_Response($data, $code ?: 200); }
    public function check_permissions() { if (get_option('verifact_public_enabled',1)) { return true; } if (get_option('verifact_require_login',0)) { return is_user_logged_in(); } $user = wp_get_current_user(); $allowed_roles = get_option(self::OPT_USER_PERMISSIONS, ['administrator']); return !empty(array_intersect($user->roles, $allowed_roles)); }
    private function log_fact_check($request, $response, $req) { global $wpdb; $table_name = $wpdb->prefix . 'verifact_logs'; $wpdb->insert($table_name, ['claim'=>$request['claim'] ?? '','stance'=>$response['results'][0]['stance'] ?? 'Unknown','confidence'=>$response['results'][0]['confidence'] ?? 0,'evidence_count'=>count($response['results'][0]['evidence'] ?? []),'runtime_sec'=>$response['meta']['runtime_sec'] ?? 0,'user_id'=>get_current_user_id() ?: null,'ip_address'=>$this->get_client_ip(),'user_agent'=>$req->get_header('user_agent'),]); }
    private function get_client_ip() { $ip_keys = ['HTTP_CLIENT_IP','HTTP_X_FORWARDED_FOR','REMOTE_ADDR']; foreach ($ip_keys as $key) { if (array_key_exists($key, $_SERVER) === true) { foreach (explode(',', $_SERVER[$key]) as $ip) { $ip = trim($ip); if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) !== false) { return $ip; } } } } return $_SERVER['REMOTE_ADDR'] ?? 'unknown'; }
    private function get_analytics_data() { global $wpdb; $table_name = $wpdb->prefix . 'verifact_logs'; $stance_counts = $wpdb->get_results("SELECT stance, COUNT(*) as count FROM $table_name GROUP BY stance"); $stance_data = ['supported'=>0,'refuted'=>0,'not_enough_evidence'=>0]; foreach ($stance_counts as $row) { $key = strtolower(str_replace(' ', '_', $row->stance)); $stance_data[$key] = $row->count; } $daily_data = $wpdb->get_results("SELECT DATE(created_at) as date, COUNT(*) as count FROM $table_name WHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY) GROUP BY DATE(created_at) ORDER BY date"); $daily_labels = []; $daily_counts = []; $date_index = []; for ($i=29; $i>=0; $i--) { $date = date('Y-m-d', strtotime("-$i days")); $daily_labels[] = date('M j', strtotime($date)); $daily_counts[] = 0; $date_index[$date] = count($daily_labels) - 1; } foreach ($daily_data as $row) { if (isset($date_index[$row->date])) { $daily_counts[$date_index[$row->date]] = (int) $row->count; } } $top_claims = $wpdb->get_results("SELECT claim, COUNT(*) as count FROM $table_name GROUP BY claim ORDER BY count DESC LIMIT 5"); return ['stance_counts'=>$stance_data,'daily_labels'=>$daily_labels,'daily_data'=>$daily_counts,'top_claims'=>$top_claims]; }
    public function ajax_bulk_check() { $nonce = isset($_POST['nonce']) ? $_POST['nonce'] : ''; if (!wp_verify_nonce($nonce, 'verifact_bulk_check') && !wp_verify_nonce($nonce, 'verifact_admin_nonce')) { wp_send_json_error('Invalid nonce'); } $claims = []; if (isset($_POST['claims'])) { $decoded = json_decode(stripslashes($_POST['claims']), true); if (is_array($decoded)) { $claims = array_filter(array_map('trim', $decoded)); } } if (empty($claims) && !empty($_FILES['file']['tmp_name'])) { $content = file_get_contents($_FILES['file']['tmp_name']); $lines = preg_split('/\r\n|\r|\n/', $content); foreach ($lines as $line) { $line = trim($line); if ($line !== '') { $claims[] = $line; } } } if (empty($claims)) { wp_send_json_error('No claims provided'); } $api_base = rtrim(get_option(self::OPT_API_BASE, home_url('/verifact')), '/'); $url = $api_base . '/check'; $results = []; $successful = 0; $failed = 0; foreach ($claims as $claim) { $payload = ['claim'=>$claim]; $res = wp_remote_post($url, ['timeout'=>45,'headers'=>['Content-Type'=>'application/json'],'body'=>wp_json_encode($payload)]); if (is_wp_error($res)) { $failed++; $results[] = ['claim'=>$claim,'stance'=>'Error','confidence'=>0]; continue; } $data = json_decode(wp_remote_retrieve_body($res), true); $r = $data['results'][0] ?? null; if ($r) { $successful++; $results[] = ['claim'=>$r['claim'] ?? $claim,'stance'=>$r['stance'] ?? 'Unknown','confidence'=>$r['confidence'] ?? 0]; } else { $failed++; $results[] = ['claim'=>$claim,'stance'=>'Unknown','confidence'=>0]; } } wp_send_json_success(['total'=>count($claims),'successful'=>$successful,'failed'=>$failed,'results'=>$results]); }
    public function ajax_get_stats() { $nonce = isset($_POST['nonce']) ? $_POST['nonce'] : ''; if (!wp_verify_nonce($nonce, 'verifact_admin_nonce')) { wp_send_json_error('Invalid nonce'); } $stats = $this->get_dashboard_stats(); wp_send_json_success($stats); }
    public function ajax_clear_cache() { $nonce = isset($_POST['nonce']) ? $_POST['nonce'] : ''; if (!wp_verify_nonce($nonce, 'verifact_admin_nonce')) { wp_send_json_error('Invalid nonce'); } wp_send_json_success(['message'=>'Cache cleared']); }
    public function ajax_get_analytics() { $nonce = isset($_POST['nonce']) ? $_POST['nonce'] : ''; if (!wp_verify_nonce($nonce, 'verifact_admin_nonce')) { wp_send_json_error('Invalid nonce'); } $data = $this->get_analytics_data(); wp_send_json_success($data); }
    public function ajax_export_analytics() { $nonce = isset($_POST['nonce']) ? $_POST['nonce'] : ''; if (!wp_verify_nonce($nonce, 'verifact_admin_nonce')) { wp_send_json_error('Invalid nonce'); } $data = $this->get_analytics_data(); $csv = "Date,Count\n"; $labels = $data['daily_labels']; $counts = $data['daily_data']; for ($i=0; $i<count($labels); $i++) { $csv .= $labels[$i] . "," . $counts[$i] . "\n"; } wp_send_json_success($csv); }
    public function ajax_export_data() { $nonce = isset($_POST['nonce']) ? $_POST['nonce'] : ''; if (!wp_verify_nonce($nonce, 'verifact_admin_nonce')) { wp_send_json_error('Invalid nonce'); } $type = isset($_POST['type']) ? sanitize_text_field($_POST['type']) : 'logs'; global $wpdb; if ($type === 'logs') { $table_name = $wpdb->prefix . 'verifact_logs'; $rows = $wpdb->get_results("SELECT id, claim, stance, confidence, evidence_count, runtime_sec, user_id, created_at FROM $table_name ORDER BY created_at DESC", ARRAY_A); $csv = "ID,Claim,Stance,Confidence,EvidenceCount,RuntimeSec,UserID,CreatedAt\n"; foreach ($rows as $r) { $csv .= sprintf("%d,%s,%s,%.3f,%d,%.2f,%s,%s\n",$r['id'],str_replace([\"\n\",\"\\r\",\",\"],[' ',' ',' '],$r['claim']),$r['stance'],(float)$r['confidence'],(int)$r['evidence_count'],(float)$r['runtime_sec'],$r['user_id']?$r['user_id']:'',$r['created_at']); } wp_send_json_success($csv); } else { wp_send_json_error('Unsupported export type'); } }
    public function ajax_create_schedule() { $nonce = isset($_POST['nonce']) ? $_POST['nonce'] : ''; if (!wp_verify_nonce($nonce, 'verifact_admin_nonce')) { wp_send_json_error('Invalid nonce'); } $name = isset($_POST['name']) ? sanitize_text_field($_POST['name']) : ''; $url = isset($_POST['url']) ? esc_url_raw($_POST['url']) : ''; $freq = isset($_POST['frequency']) ? sanitize_text_field($_POST['frequency']) : 'daily'; if (!$name || !$url || !in_array($freq, ['daily','weekly','monthly'], true)) { wp_send_json_error('Invalid schedule'); } $schedules = get_option('verifact_schedules', []); $schedules[] = ['name'=>$name,'url'=>$url,'frequency'=>$freq,'last_run'=>0,'created_at'=>time()]; update_option('verifact_schedules', $schedules, false); wp_send_json_success(['message'=>'Schedule created']); }
    public function extend_cron_schedules($schedules) { $schedules['weekly'] = ['interval'=>7*86400,'display'=>'Once Weekly']; $schedules['monthly'] = ['interval'=>30*86400,'display'=>'Once Monthly']; return $schedules; }
    public function ensure_cron() { if (!wp_next_scheduled('verifact_run_schedules')) { wp_schedule_event(time(), 'hourly', 'verifact_run_schedules'); } }
    public function run_schedules() { $schedules = get_option('verifact_schedules', []); $now = time(); $updated = false; foreach ($schedules as &$s) { $interval = 86400; if ($s['frequency'] === 'weekly') { $interval = 7*86400; } if ($s['frequency'] === 'monthly') { $interval = 30*86400; } if ($now - (int)$s['last_run'] >= $interval) { $s['last_run'] = $now; $updated = true; } } if ($updated) { update_option('verifact_schedules', $schedules, false); } $this->upload_remote_cache(); }
    private function enforce_rate_limit() { $limit = (int) get_option(self::OPT_RATE_LIMIT, 100); $override = get_option('verifact_role_rate_limits', ''); if ($override) { $map = json_decode($override, true); if (is_array($map)) { $user = wp_get_current_user(); foreach ($user->roles as $role) { if (isset($map[$role]) && is_numeric($map[$role])) { $limit = (int) $map[$role]; break; } } } } if ($limit <= 0) { return true; } $user_id = get_current_user_id(); $key = $user_id ? 'u_'.$user_id : 'ip_'.$this->get_client_ip(); $transient = 'verifact_rate_'.$key; $data = get_transient($transient); $now = time(); if (!$data || !isset($data['reset']) || $now >= $data['reset']) { set_transient($transient, ['count'=>1,'reset'=>$now+3600], 3600); return true; } if ($data['count'] >= $limit) { return false; } $data['count']++; set_transient($transient, $data, $data['reset'] - $now); return true; }
    private function cache_get($key) { if (function_exists('wp_cache_get')) { $val = wp_cache_get($key, 'verifact'); if ($val !== false) { return $val; } } return get_transient($key); }
    private function cache_set($key, $value, $ttl) { if (function_exists('wp_cache_set')) { wp_cache_set($key, $value, 'verifact', $ttl); } else { set_transient($key, $value, $ttl); } }
    private function upload_remote_cache() { if (!get_option('verifact_remote_cache_enabled', 0)) { return; } $url = get_option('verifact_remote_cache_url', ''); if (!$url) { return; } global $wpdb; $table = $wpdb->prefix . 'verifact_logs'; $rows = $wpdb->get_results("SELECT claim, COUNT(*) as count FROM $table GROUP BY claim ORDER BY count DESC LIMIT 20", ARRAY_A); $payload = ['generated_at'=>gmdate('c'),'top_claims'=>$rows]; wp_remote_request($url, ['method'=>'PUT','headers'=>['Content-Type'=>'application/json'],'body'=>wp_json_encode($payload),'timeout'=>20]); }
    public function ajax_upload_remote_cache() { $nonce = isset($_POST['nonce']) ? $_POST['nonce'] : ''; if (!wp_verify_nonce($nonce, 'verifact_admin_nonce')) { wp_send_json_error('Invalid nonce'); } if (!get_option('verifact_remote_cache_enabled', 0)) { wp_send_json_error('Remote cache disabled'); } if (!get_option('verifact_remote_cache_url', '')) { wp_send_json_error('Remote cache URL not set'); } $this->upload_remote_cache(); wp_send_json_success(true); }
    public function ajax_get_log() { $nonce = isset($_POST['nonce']) ? $_POST['nonce'] : ''; if (!wp_verify_nonce($nonce, 'verifact_admin_nonce')) { wp_send_json_error('Invalid nonce'); } $id = isset($_POST['id']) ? intval($_POST['id']) : 0; if ($id <= 0) { wp_send_json_error('Invalid id'); } global $wpdb; $table = $wpdb->prefix . 'verifact_logs'; $row = $wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE id = %d", $id), ARRAY_A); if (!$row) { wp_send_json_error('Not found'); } wp_send_json_success($row); }
    public function ajax_get_user_stats() { $nonce = isset($_POST['nonce']) ? $_POST['nonce'] : ''; if (!wp_verify_nonce($nonce, 'verifact_admin_nonce')) { wp_send_json_error('Invalid nonce'); } $user_id = isset($_POST['user_id']) ? intval($_POST['user_id']) : 0; if ($user_id <= 0) { wp_send_json_error('Invalid user'); } global $wpdb; $table = $wpdb->prefix . 'verifact_logs'; $total = $wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM $table WHERE user_id = %d", $user_id)); $last = $wpdb->get_var($wpdb->prepare("SELECT created_at FROM $table WHERE user_id = %d ORDER BY created_at DESC LIMIT 1", $user_id)); $stances = $wpdb->get_results($wpdb->prepare("SELECT stance, COUNT(*) as count FROM $table WHERE user_id = %d GROUP BY stance", $user_id), ARRAY_A); wp_send_json_success(['total'=>intval($total),'last_activity'=>$last,'stances'=>$stances]); }
    private function get_api_call_count() { global $wpdb; $table_name = $wpdb->prefix . 'verifact_logs'; return $wpdb->get_var("SELECT COUNT(*) FROM $table_name"); }
    private function get_successful_api_calls() { global $wpdb; $table_name = $wpdb->prefix . 'verifact_logs'; return $wpdb->get_var("SELECT COUNT(*) FROM $table_name WHERE confidence > 0"); }
    private function get_failed_api_calls() { global $wpdb; $table_name = $wpdb->prefix . 'verifact_logs'; return $wpdb->get_var("SELECT COUNT(*) FROM $table_name WHERE confidence = 0"); }
    private function get_avg_response_time() { global $wpdb; $table_name = $wpdb->prefix . 'verifact_logs'; return $wpdb->get_var("SELECT AVG(runtime_sec) FROM $table_name") ?: 0; }
    private function get_user_fact_check_count($user_id) { global $wpdb; $table_name = $wpdb->prefix . 'verifact_logs'; return $wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM $table_name WHERE user_id = %d", $user_id)); }
    private function get_user_last_activity($user_id) { global $wpdb; $table_name = $wpdb->prefix . 'verifact_logs'; $last_activity = $wpdb->get_var($wpdb->prepare("SELECT created_at FROM $table_name WHERE user_id = %d ORDER BY created_at DESC LIMIT 1", $user_id)); return $last_activity ? human_time_diff(strtotime($last_activity)) . ' ago' : 'Never'; }
    private function get_active_users_count() { global $wpdb; $table_name = $wpdb->prefix . 'verifact_logs'; return $wpdb->get_var("SELECT COUNT(DISTINCT user_id) FROM $table_name WHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)"); }
    private function get_most_active_user() { global $wpdb; $table_name = $wpdb->prefix . 'verifact_logs'; $user_id = $wpdb->get_var("SELECT user_id FROM $table_name GROUP BY user_id ORDER BY COUNT(*) DESC LIMIT 1"); return $user_id ? get_userdata($user_id)->display_name : 'None'; }
    private function sanitize_user_permissions($permissions) { if (!is_array($permissions)) { return ['administrator']; } $valid_roles = array_keys(get_editable_roles()); return array_intersect($permissions, $valid_roles); }
}
new VeriFactPlugin();
