<?php
$root=dirname(__DIR__);$plugin=file_get_contents($root.'/verifact-plugin.php');$failures=[];
$expect=static function(bool $condition,string $message)use(&$failures):void{if(!$condition){$failures[]=$message;}};
$expect(str_contains($plugin,'Version: 3.4.0'),'Version header must be 3.4.0');
$expect(str_contains($plugin,"register_activation_hook(__FILE__"),'Activation hook is required');
$expect(str_contains($plugin,'permission_callback'),'REST permission callbacks are required');
$expect(str_contains($plugin,"getenv('VERIFACT_API_KEY')"),'Server-injected API key mapping is required');
$expect(!str_contains($plugin,"get_option('verifact_api_key'"),'API keys must not be stored in WordPress options');
$expect(str_contains($plugin,'wp_safe_remote_post'),'Safe upstream requests are required');
foreach(['editor','privacy','diagnostics','queue','compatibility','workflow','evidence','enterprise','support','bulk','platform','subscription'] as $module){$expect(is_file($root.'/includes/class-verifact-'.$module.'.php'),ucfirst($module).' module is required');}
$queue=file_get_contents($root.'/includes/class-verifact-queue.php');
$expect(str_contains($queue,'verifact_jobs'),'Durable database queue is required');
$expect(str_contains($queue,'as_schedule_recurring_action'),'Action Scheduler integration is required');
$expect(str_contains($queue,'claims_reused'),'Revision-aware claim reuse is required');
$expect(str_contains($queue,"WP_CLI::add_command('verifact queue run'"),'System-cron/CLI queue runner is required');
$workflow=file_get_contents($root.'/includes/class-verifact-workflow.php');
$expect(str_contains($workflow,'publication_override'),'Audited publication overrides are required');
$evidence=file_get_contents($root.'/includes/class-verifact-evidence.php');
$expect(str_contains($evidence,"'ClaimReview'"),'Human-approved ClaimReview markup is required');
$support=file_get_contents($root.'/includes/class-verifact-support.php');
$expect(str_contains($support,"'redaction'"),'Redacted support bundle is required');
$enterprise=file_get_contents($root.'/includes/class-verifact-enterprise.php');
$expect(str_contains($enterprise,'VERIFACT_ALLOWED_API_HOSTS'),'Outbound host restrictions are required');
$expect(str_contains($plugin,'wp_initialize_site'),'New multisite sites must be initialized');
$expect(str_contains($plugin,'get_sites'),'Network activation must install every site');
$compatibility=file_get_contents($root.'/includes/class-verifact-compatibility.php');
$expect(str_contains($compatibility,'verifact_post_content'),'Page-builder extraction filter is required');
$expect(str_contains($compatibility,"'_elementor_data'"),'Elementor content extraction is required');
$expect(str_contains($workflow,"'content_hash'"),'Publication overrides must be content-revision bound');
$expect(str_contains($evidence,"'content_hash'"),'ClaimReview approval must be content-revision bound');
$expect(str_contains($queue,'verifact_claim_reuse_days'),'Claim reuse must have a freshness policy');
$expect(str_contains($plugin,'connection_report'),'Authenticated connection report is required');
$expect(str_contains($plugin,"'/api/v1/capabilities'"),'Capabilities handshake is required');
$expect(str_contains($plugin,"'/api/v1/auth/whoami'"),'Credential identity handshake is required');
$expect(str_contains($plugin,"'/api/v1/connection/test'"),'Authenticated connection test is required');
$expect(str_contains($plugin,"'VeriFact-Client-Version'"),'Client version negotiation header is required');
$expect(str_contains($plugin,'verifact_api_circuit'),'Transient failure circuit breaker is required');
$expect(str_contains($plugin,'verify_provenance'),'Response provenance verification is required');
$expect(str_contains($queue,"'dead_letter'"),'Dead-letter queue state is required');
$expect(str_contains($queue,'function requeue'),'Dead-letter recovery is required');
$subscription=file_get_contents($root.'/includes/class-verifact-subscription.php');
$expect(str_contains($subscription,"'/api/v1/billing/checkout-session'"),'Hosted subscription checkout is required');
$expect(str_contains($subscription,"'/api/v1/licenses/activate'"),'One-time license activation is required');
$expect(str_contains($subscription,'sodium_crypto_sign_detached'),'Site-bound Ed25519 authentication is required');
$expect(!str_contains($subscription,'update_option(self::LICENSE_STATUS,$license'),'Raw license keys must not be stored');
$expect(str_contains($plugin,"apply_filters('verifact_api_bearer_token'"),'Short-lived bearer token transport is required');
$bulk=file_get_contents($root.'/includes/class-verifact-bulk.php');
$expect(str_contains($bulk,"'/bulk/queue'"),'Bulk queue REST endpoint is required');
$expect(str_contains($bulk,"WP_CLI::add_command('verifact bulk queue'"),'Bulk queue CLI is required');preg_match_all("/\[\$this,'([A-Za-z0-9_]+)'\]/",$plugin,$references);preg_match_all('/function\s+([A-Za-z0-9_]+)\s*\(/',$plugin,$definitions);$missing=array_diff(array_unique($references[1]),array_unique($definitions[1]));$expect($missing===[],'Undefined callbacks: '.implode(', ',$missing));
if($failures){fwrite(STDERR,implode(PHP_EOL,$failures).PHP_EOL);exit(1);}echo "VeriFact 3.4 structural checks passed.\n";
